version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '4090:4090'
      - '9000:9000'
    environment:
      NODE_ENV: development
    volumes:
      - .:/app
    command: sh -c "npm run dev & npm run api && wait"
